/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CheckIfEmailExistSMTP model module.
* @module model/CheckIfEmailExistSMTP
* @version 0.0.1
*/
export default class CheckIfEmailExistSMTP {
    /**
    * Constructs a new <code>CheckIfEmailExistSMTP</code>.
    * @alias module:model/CheckIfEmailExistSMTP
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CheckIfEmailExistSMTP</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CheckIfEmailExistSMTP} obj Optional instance to populate.
    * @return {module:model/CheckIfEmailExistSMTP} The populated <code>CheckIfEmailExistSMTP</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckIfEmailExistSMTP();
                        
            
            if (data.hasOwnProperty('can_connect_smtp')) {
                obj['can_connect_smtp'] = ApiClient.convertToType(data['can_connect_smtp'], 'Boolean');
            }
            if (data.hasOwnProperty('has_full_inbox')) {
                obj['has_full_inbox'] = ApiClient.convertToType(data['has_full_inbox'], 'Boolean');
            }
            if (data.hasOwnProperty('is_catch_all')) {
                obj['is_catch_all'] = ApiClient.convertToType(data['is_catch_all'], 'Boolean');
            }
            if (data.hasOwnProperty('is_deliverable')) {
                obj['is_deliverable'] = ApiClient.convertToType(data['is_deliverable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_disabled')) {
                obj['is_disabled'] = ApiClient.convertToType(data['is_disabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} can_connect_smtp
    */
    'can_connect_smtp' = undefined;
    /**
    * @member {Boolean} has_full_inbox
    */
    'has_full_inbox' = undefined;
    /**
    * @member {Boolean} is_catch_all
    */
    'is_catch_all' = undefined;
    /**
    * @member {Boolean} is_deliverable
    */
    'is_deliverable' = undefined;
    /**
    * @member {Boolean} is_disabled
    */
    'is_disabled' = undefined;




}
