/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CheckIfEmailExistSyntax model module.
* @module model/CheckIfEmailExistSyntax
* @version 0.0.1
*/
export default class CheckIfEmailExistSyntax {
    /**
    * Constructs a new <code>CheckIfEmailExistSyntax</code>.
    * @alias module:model/CheckIfEmailExistSyntax
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CheckIfEmailExistSyntax</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CheckIfEmailExistSyntax} obj Optional instance to populate.
    * @return {module:model/CheckIfEmailExistSyntax} The populated <code>CheckIfEmailExistSyntax</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckIfEmailExistSyntax();
                        
            
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('is_valid_syntax')) {
                obj['is_valid_syntax'] = ApiClient.convertToType(data['is_valid_syntax'], 'Boolean');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} address
    */
    'address' = undefined;
    /**
    * @member {String} domain
    */
    'domain' = undefined;
    /**
    * @member {Boolean} is_valid_syntax
    */
    'is_valid_syntax' = undefined;
    /**
    * @member {String} username
    */
    'username' = undefined;




}
