/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The EmailResponse model module.
* @module model/EmailResponse
* @version 0.0.1
*/
export default class EmailResponse {
    /**
    * Constructs a new <code>EmailResponse</code>.
    * @alias module:model/EmailResponse
    * @class
    */

    constructor() {
        
        OneOfEmailResponse.call(this);
        
    }

    /**
    * Constructs a <code>EmailResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmailResponse} obj Optional instance to populate.
    * @return {module:model/EmailResponse} The populated <code>EmailResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailResponse();
                        
            
        }
        return obj;
    }


    // Implement OneOfEmailResponse interface:
    


}
