/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmailRequestSmtp from './EmailRequestSmtp';
import ResultType from './ResultType';

/**
* The EmailRequest model module.
* @module model/EmailRequest
* @version 0.0.1
*/
export default class EmailRequest {
    /**
    * Constructs a new <code>EmailRequest</code>.
    * @alias module:model/EmailRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>EmailRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmailRequest} obj Optional instance to populate.
    * @return {module:model/EmailRequest} The populated <code>EmailRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailRequest();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('smtp')) {
                obj['smtp'] = EmailRequestSmtp.constructFromObject(data['smtp']);
            }
            if (data.hasOwnProperty('result_type')) {
                obj['result_type'] = ResultType.constructFromObject(data['result_type']);
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {module:model/EmailRequestSmtp} smtp
    */
    'smtp' = undefined;
    /**
    * @member {module:model/ResultType} result_type
    */
    'result_type' = undefined;




}
