/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The EmailRequestSmtp model module.
* @module model/EmailRequestSmtp
* @version 0.0.1
*/
export default class EmailRequestSmtp {
    /**
    * Constructs a new <code>EmailRequestSmtp</code>.
    * @alias module:model/EmailRequestSmtp
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>EmailRequestSmtp</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmailRequestSmtp} obj Optional instance to populate.
    * @return {module:model/EmailRequestSmtp} The populated <code>EmailRequestSmtp</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailRequestSmtp();
                        
            
            if (data.hasOwnProperty('email_from')) {
                obj['email_from'] = ApiClient.convertToType(data['email_from'], 'String');
            }
            if (data.hasOwnProperty('hello_name')) {
                obj['hello_name'] = ApiClient.convertToType(data['hello_name'], 'String');
            }
            if (data.hasOwnProperty('proxy')) {
                obj['proxy'] = ApiClient.convertToType(data['proxy'], 'String');
            }
            if (data.hasOwnProperty('timeout_connection')) {
                obj['timeout_connection'] = ApiClient.convertToType(data['timeout_connection'], 'Number');
            }
            if (data.hasOwnProperty('timeout_response')) {
                obj['timeout_response'] = ApiClient.convertToType(data['timeout_response'], 'Number');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} email_from
    */
    'email_from' = undefined;
    /**
    * @member {String} hello_name
    * @default 'localhost'
    */
    'hello_name' = 'localhost';
    /**
    * Versions - SOCKS4, SOCKS4A and SOCKS5. Format -  schema://username:password@host:port. 
    * @member {String} proxy
    */
    'proxy' = undefined;
    /**
    * timeout creating smtp connection
    * @member {Number} timeout_connection
    * @default 5.0
    */
    'timeout_connection' = 5.0;
    /**
    * timeout of communication with smtp server
    * @member {Number} timeout_response
    */
    'timeout_response' = undefined;
    /**
    * smtp port remote server
    * @member {Number} port
    * @default 25
    */
    'port' = 25;




}
