/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MailboxvalidatorResult model module.
* @module model/MailboxvalidatorResult
* @version 0.0.1
*/
export default class MailboxvalidatorResult {
    /**
    * Constructs a new <code>MailboxvalidatorResult</code>.
    * @alias module:model/MailboxvalidatorResult
    * @class
    */

    constructor() {
        
        OneOfEmailResponse.call(this);
        
    }

    /**
    * Constructs a <code>MailboxvalidatorResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MailboxvalidatorResult} obj Optional instance to populate.
    * @return {module:model/MailboxvalidatorResult} The populated <code>MailboxvalidatorResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MailboxvalidatorResult();
                        
            
            if (data.hasOwnProperty('email_address')) {
                obj['email_address'] = ApiClient.convertToType(data['email_address'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('is_free')) {
                obj['is_free'] = ApiClient.convertToType(data['is_free'], 'String');
            }
            if (data.hasOwnProperty('is_syntax')) {
                obj['is_syntax'] = ApiClient.convertToType(data['is_syntax'], 'String');
            }
            if (data.hasOwnProperty('is_domain')) {
                obj['is_domain'] = ApiClient.convertToType(data['is_domain'], 'String');
            }
            if (data.hasOwnProperty('is_smtp')) {
                obj['is_smtp'] = ApiClient.convertToType(data['is_smtp'], 'String');
            }
            if (data.hasOwnProperty('is_verified')) {
                obj['is_verified'] = ApiClient.convertToType(data['is_verified'], 'String');
            }
            if (data.hasOwnProperty('is_server_down')) {
                obj['is_server_down'] = ApiClient.convertToType(data['is_server_down'], 'String');
            }
            if (data.hasOwnProperty('is_greylisted')) {
                obj['is_greylisted'] = ApiClient.convertToType(data['is_greylisted'], 'String');
            }
            if (data.hasOwnProperty('is_disposable')) {
                obj['is_disposable'] = ApiClient.convertToType(data['is_disposable'], 'String');
            }
            if (data.hasOwnProperty('is_suppressed')) {
                obj['is_suppressed'] = ApiClient.convertToType(data['is_suppressed'], 'String');
            }
            if (data.hasOwnProperty('is_role')) {
                obj['is_role'] = ApiClient.convertToType(data['is_role'], 'String');
            }
            if (data.hasOwnProperty('is_high_risk')) {
                obj['is_high_risk'] = ApiClient.convertToType(data['is_high_risk'], 'String');
            }
            if (data.hasOwnProperty('is_catchall')) {
                obj['is_catchall'] = ApiClient.convertToType(data['is_catchall'], 'String');
            }
            if (data.hasOwnProperty('mailboxvalidator_score')) {
                obj['mailboxvalidator_score'] = ApiClient.convertToType(data['mailboxvalidator_score'], 'String');
            }
            if (data.hasOwnProperty('time_taken')) {
                obj['time_taken'] = ApiClient.convertToType(data['time_taken'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('credits_available')) {
                obj['credits_available'] = ApiClient.convertToType(data['credits_available'], 'Number');
            }
            if (data.hasOwnProperty('error_code')) {
                obj['error_code'] = ApiClient.convertToType(data['error_code'], 'String');
            }
            if (data.hasOwnProperty('error_message')) {
                obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email_address
    */
    'email_address' = undefined;
    /**
    * @member {String} domain
    */
    'domain' = undefined;
    /**
    * @member {String} is_free
    */
    'is_free' = undefined;
    /**
    * @member {String} is_syntax
    */
    'is_syntax' = undefined;
    /**
    * @member {String} is_domain
    */
    'is_domain' = undefined;
    /**
    * @member {String} is_smtp
    */
    'is_smtp' = undefined;
    /**
    * @member {String} is_verified
    */
    'is_verified' = undefined;
    /**
    * @member {String} is_server_down
    */
    'is_server_down' = undefined;
    /**
    * @member {String} is_greylisted
    */
    'is_greylisted' = undefined;
    /**
    * @member {String} is_disposable
    */
    'is_disposable' = undefined;
    /**
    * @member {String} is_suppressed
    */
    'is_suppressed' = undefined;
    /**
    * @member {String} is_role
    */
    'is_role' = undefined;
    /**
    * @member {String} is_high_risk
    */
    'is_high_risk' = undefined;
    /**
    * @member {String} is_catchall
    */
    'is_catchall' = undefined;
    /**
    * @member {String} mailboxvalidator_score
    */
    'mailboxvalidator_score' = undefined;
    /**
    * @member {String} time_taken
    */
    'time_taken' = undefined;
    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {Number} credits_available
    */
    'credits_available' = undefined;
    /**
    * @member {String} error_code
    */
    'error_code' = undefined;
    /**
    * @member {String} error_message
    */
    'error_message' = undefined;

    // Implement OneOfEmailResponse interface:
    


}
