/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PromptEmailVerificationApiMX from './PromptEmailVerificationApiMX';

/**
* The PromptEmailVerificationApiResult model module.
* @module model/PromptEmailVerificationApiResult
* @version 0.0.1
*/
export default class PromptEmailVerificationApiResult {
    /**
    * Constructs a new <code>PromptEmailVerificationApiResult</code>.
    * @alias module:model/PromptEmailVerificationApiResult
    * @class
    */

    constructor() {
        
        OneOfEmailResponse.call(this);
        
    }

    /**
    * Constructs a <code>PromptEmailVerificationApiResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PromptEmailVerificationApiResult} obj Optional instance to populate.
    * @return {module:model/PromptEmailVerificationApiResult} The populated <code>PromptEmailVerificationApiResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromptEmailVerificationApiResult();
                        
            
            if (data.hasOwnProperty('can_connect_smtp')) {
                obj['can_connect_smtp'] = ApiClient.convertToType(data['can_connect_smtp'], 'Boolean');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('is_catch_all')) {
                obj['is_catch_all'] = ApiClient.convertToType(data['is_catch_all'], 'Boolean');
            }
            if (data.hasOwnProperty('is_deliverable')) {
                obj['is_deliverable'] = ApiClient.convertToType(data['is_deliverable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_disabled')) {
                obj['is_disabled'] = ApiClient.convertToType(data['is_disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('is_disposable')) {
                obj['is_disposable'] = ApiClient.convertToType(data['is_disposable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_inbox_full')) {
                obj['is_inbox_full'] = ApiClient.convertToType(data['is_inbox_full'], 'Boolean');
            }
            if (data.hasOwnProperty('is_role_account')) {
                obj['is_role_account'] = ApiClient.convertToType(data['is_role_account'], 'Boolean');
            }
            if (data.hasOwnProperty('mx_records')) {
                obj['mx_records'] = PromptEmailVerificationApiMX.constructFromObject(data['mx_records']);
            }
            if (data.hasOwnProperty('syntax_valid')) {
                obj['syntax_valid'] = ApiClient.convertToType(data['syntax_valid'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} can_connect_smtp
    */
    'can_connect_smtp' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {Boolean} is_catch_all
    */
    'is_catch_all' = undefined;
    /**
    * @member {Boolean} is_deliverable
    */
    'is_deliverable' = undefined;
    /**
    * @member {Boolean} is_disabled
    */
    'is_disabled' = undefined;
    /**
    * @member {Boolean} is_disposable
    */
    'is_disposable' = undefined;
    /**
    * @member {Boolean} is_inbox_full
    */
    'is_inbox_full' = undefined;
    /**
    * @member {Boolean} is_role_account
    */
    'is_role_account' = undefined;
    /**
    * @member {module:model/PromptEmailVerificationApiMX} mx_records
    */
    'mx_records' = undefined;
    /**
    * @member {Boolean} syntax_valid
    */
    'syntax_valid' = undefined;
    /**
    * @member {String} message
    */
    'message' = undefined;

    // Implement OneOfEmailResponse interface:
    


}
