/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UnexpectedError model module.
* @module model/UnexpectedError
* @version 0.0.1
*/
export default class UnexpectedError {
    /**
    * Constructs a new <code>UnexpectedError</code>.
    * @alias module:model/UnexpectedError
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UnexpectedError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UnexpectedError} obj Optional instance to populate.
    * @return {module:model/UnexpectedError} The populated <code>UnexpectedError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnexpectedError();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], {'String': Object});
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    'code' = undefined;
    /**
    * @member {String} message
    */
    'message' = undefined;
    /**
    * @member {Object.<String, Object>} details
    */
    'details' = undefined;




}
