<?php
/**
 * EmailRequestSmtp
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EmailRequestSmtp Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmailRequestSmtp implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EmailRequest_smtp';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'email_from' => 'string',
'hello_name' => 'string',
'proxy' => 'string',
'timeout_connection' => 'float',
'timeout_response' => 'float',
'port' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'email_from' => 'email',
'hello_name' => null,
'proxy' => 'uri',
'timeout_connection' => null,
'timeout_response' => null,
'port' => 'int32'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email_from' => 'email_from',
'hello_name' => 'hello_name',
'proxy' => 'proxy',
'timeout_connection' => 'timeout_connection',
'timeout_response' => 'timeout_response',
'port' => 'port'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email_from' => 'setEmailFrom',
'hello_name' => 'setHelloName',
'proxy' => 'setProxy',
'timeout_connection' => 'setTimeoutConnection',
'timeout_response' => 'setTimeoutResponse',
'port' => 'setPort'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email_from' => 'getEmailFrom',
'hello_name' => 'getHelloName',
'proxy' => 'getProxy',
'timeout_connection' => 'getTimeoutConnection',
'timeout_response' => 'getTimeoutResponse',
'port' => 'getPort'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['email_from'] = isset($data['email_from']) ? $data['email_from'] : null;
        $this->container['hello_name'] = isset($data['hello_name']) ? $data['hello_name'] : 'localhost';
        $this->container['proxy'] = isset($data['proxy']) ? $data['proxy'] : null;
        $this->container['timeout_connection'] = isset($data['timeout_connection']) ? $data['timeout_connection'] : null;
        $this->container['timeout_response'] = isset($data['timeout_response']) ? $data['timeout_response'] : null;
        $this->container['port'] = isset($data['port']) ? $data['port'] : 25;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email_from
     *
     * @return string
     */
    public function getEmailFrom()
    {
        return $this->container['email_from'];
    }

    /**
     * Sets email_from
     *
     * @param string $email_from email_from
     *
     * @return $this
     */
    public function setEmailFrom($email_from)
    {
        $this->container['email_from'] = $email_from;

        return $this;
    }

    /**
     * Gets hello_name
     *
     * @return string
     */
    public function getHelloName()
    {
        return $this->container['hello_name'];
    }

    /**
     * Sets hello_name
     *
     * @param string $hello_name hello_name
     *
     * @return $this
     */
    public function setHelloName($hello_name)
    {
        $this->container['hello_name'] = $hello_name;

        return $this;
    }

    /**
     * Gets proxy
     *
     * @return string
     */
    public function getProxy()
    {
        return $this->container['proxy'];
    }

    /**
     * Sets proxy
     *
     * @param string $proxy Versions - SOCKS4, SOCKS4A and SOCKS5. Format -  schema://username:password@host:port.
     *
     * @return $this
     */
    public function setProxy($proxy)
    {
        $this->container['proxy'] = $proxy;

        return $this;
    }

    /**
     * Gets timeout_connection
     *
     * @return float
     */
    public function getTimeoutConnection()
    {
        return $this->container['timeout_connection'];
    }

    /**
     * Sets timeout_connection
     *
     * @param float $timeout_connection timeout creating smtp connection
     *
     * @return $this
     */
    public function setTimeoutConnection($timeout_connection)
    {
        $this->container['timeout_connection'] = $timeout_connection;

        return $this;
    }

    /**
     * Gets timeout_response
     *
     * @return float
     */
    public function getTimeoutResponse()
    {
        return $this->container['timeout_response'];
    }

    /**
     * Sets timeout_response
     *
     * @param float $timeout_response timeout of communication with smtp server
     *
     * @return $this
     */
    public function setTimeoutResponse($timeout_response)
    {
        $this->container['timeout_response'] = $timeout_response;

        return $this;
    }

    /**
     * Gets port
     *
     * @return int
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param int $port smtp port remote server
     *
     * @return $this
     */
    public function setPort($port)
    {
        $this->container['port'] = $port;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
