<?php
/**
 * ResultType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ResultType Class Doc Comment
 *
 * @category Class
 * @description * CHECK_IF_EMAIL_EXIST, CIEE - [check-if-email-exists format](https://github.com/amaurymartiny/check-if-email-exists#%EF%B8%8F-json-output). * MAILBOXVALIDATOR, MAIL_BOX_VALIDATOR, MBV - [mailboxvalidator.com format](https://www.mailboxvalidator.com/api-single-validation). * PROMPT_EMAIL_VERIFICATION_API, PEVA - [Email Verification api format](https://promptapi.com/marketplace/description/email_verification-api) from [promptapi](https://promptapi.com).
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResultType
{
    /**
     * Possible values of this enum
     */
    const CHECK_IF_EMAIL_EXIST = 'CHECK_IF_EMAIL_EXIST';
const CIEE = 'CIEE';
const MAILBOXVALIDATOR = 'MAILBOXVALIDATOR';
const MAIL_BOX_VALIDATOR = 'MAIL_BOX_VALIDATOR';
const MBV = 'MBV';
const PROMPT_EMAIL_VERIFICATION_API = 'PROMPT_EMAIL_VERIFICATION_API';
const PEVA = 'PEVA';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHECK_IF_EMAIL_EXIST,
self::CIEE,
self::MAILBOXVALIDATOR,
self::MAIL_BOX_VALIDATOR,
self::MBV,
self::PROMPT_EMAIL_VERIFICATION_API,
self::PEVA,        ];
    }
}
