/**
 * Email Validator
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import EmailRequest from '../model/EmailRequest';
import EmailResponse from '../model/EmailResponse';
import ResultType from '../model/ResultType';
import UnexpectedError from '../model/UnexpectedError';

/**
* EmailValidation service.
* @module api/EmailValidationApi
* @version 0.0.1
*/
export default class EmailValidationApi {

    /**
    * Constructs a new EmailValidationApi. 
    * @alias module:api/EmailValidationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the emailValidationSingleValidationGet operation.
     * @callback module:api/EmailValidationApi~emailValidationSingleValidationGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmailResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * POST request contains additional parameters for detailed configuration
     * @param {Object} opts Optional parameters
     * @param {module:api/EmailValidationApi~emailValidationSingleValidationGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmailResponse}
     */
    emailValidationSingleValidationGet(email, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'email': email
      };
      let queryParams = {
        'result_type': opts['resultType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AuthKey', 'RapidApiKey', 'RapidApiSecret'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EmailResponse;

      return this.apiClient.callApi(
        '/v1/validation/single/{email}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the emailValidationSingleValidationPost operation.
     * @callback module:api/EmailValidationApi~emailValidationSingleValidationPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmailResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/EmailValidationApi~emailValidationSingleValidationPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmailResponse}
     */
    emailValidationSingleValidationPost(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AuthKey', 'RapidApiKey', 'RapidApiSecret'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EmailResponse;

      return this.apiClient.callApi(
        '/v1/validation/single', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
