openapi: 3.0.0
info:
  description: |
    All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
  title: Email Validator
  version: 0.0.1
servers:
- url: /
- url: https://email-validator15.p.rapidapi.com/
security:
- AuthKey: []
- RapidApiSecret: []
- RapidApiKey: []
paths:
  /v1/validation/single:
    post:
      operationId: EmailValidation_singleValidation_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
          description: An unexpected error response.
      tags:
      - EmailValidation
      x-codegen-request-body-name: body
  /v1/validation/single/{email}:
    get:
      description: POST request contains additional parameters for detailed configuration
      operationId: EmailValidation_singleValidation_get
      parameters:
      - explode: false
        in: path
        name: email
        required: true
        schema:
          type: string
        style: simple
      - description: ResultTypeDescription
        explode: true
        in: query
        name: result_type
        required: false
        schema:
          $ref: '#/components/schemas/ResultType'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
          description: An unexpected error response.
      tags:
      - EmailValidation
components:
  schemas:
    ResultType:
      default: CHECK_IF_EMAIL_EXIST
      description: |
        * CHECK_IF_EMAIL_EXIST, CIEE - [check-if-email-exists format](https://github.com/amaurymartiny/check-if-email-exists#%EF%B8%8F-json-output).
        * MAILBOXVALIDATOR, MAIL_BOX_VALIDATOR, MBV - [mailboxvalidator.com format](https://www.mailboxvalidator.com/api-single-validation).
        * PROMPT_EMAIL_VERIFICATION_API, PEVA - [Email Verification api format](https://promptapi.com/marketplace/description/email_verification-api) from [promptapi](https://promptapi.com).
      enum:
      - CHECK_IF_EMAIL_EXIST
      - CIEE
      - MAILBOXVALIDATOR
      - MAIL_BOX_VALIDATOR
      - MBV
      - PROMPT_EMAIL_VERIFICATION_API
      - PEVA
      title: ResultType
      type: string
    CheckIfEmailExistMisc:
      properties:
        is_disposable:
          type: boolean
        is_role_account:
          type: boolean
      type: object
    CheckIfEmailExistSMTP:
      properties:
        can_connect_smtp:
          type: boolean
        has_full_inbox:
          type: boolean
        is_catch_all:
          type: boolean
        is_deliverable:
          type: boolean
        is_disabled:
          type: boolean
      type: object
    CheckIfEmailExistSyntax:
      properties:
        address:
          type: string
        domain:
          type: string
        is_valid_syntax:
          type: boolean
        username:
          type: string
      type: object
    CheckIfEmailExistMX:
      properties:
        accepts_mail:
          type: boolean
        records:
          items:
            type: string
          type: array
      type: object
    CheckIfEmailExistResult:
      properties:
        input:
          type: string
        is_reachable:
          type: string
        misc:
          $ref: '#/components/schemas/CheckIfEmailExistMisc'
        mx:
          $ref: '#/components/schemas/CheckIfEmailExistMX'
        smtp:
          $ref: '#/components/schemas/CheckIfEmailExistSMTP'
        syntax:
          $ref: '#/components/schemas/CheckIfEmailExistSyntax'
        error:
          type: string
      type: object
    MailboxvalidatorResult:
      properties:
        email_address:
          type: string
        domain:
          type: string
        is_free:
          type: string
        is_syntax:
          type: string
        is_domain:
          type: string
        is_smtp:
          type: string
        is_verified:
          type: string
        is_server_down:
          type: string
        is_greylisted:
          type: string
        is_disposable:
          type: string
        is_suppressed:
          type: string
        is_role:
          type: string
        is_high_risk:
          type: string
        is_catchall:
          type: string
        mailboxvalidator_score:
          type: string
        time_taken:
          type: string
        status:
          type: string
        credits_available:
          format: int64
          type: integer
        error_code:
          type: string
        error_message:
          type: string
      type: object
    PromptEmailVerificationApiResult:
      properties:
        can_connect_smtp:
          type: boolean
        email:
          type: string
        is_catch_all:
          type: boolean
        is_deliverable:
          type: boolean
        is_disabled:
          type: boolean
        is_disposable:
          type: boolean
        is_inbox_full:
          type: boolean
        is_role_account:
          type: boolean
        mx_records:
          $ref: '#/components/schemas/PromptEmailVerificationApiMX'
        syntax_valid:
          type: boolean
        message:
          type: string
      type: object
    PromptEmailVerificationApiMX:
      properties:
        accepts_mail:
          type: boolean
        records:
          items:
            type: string
          type: array
      type: object
    UnexpectedError:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          additionalProperties: true
          type: object
      type: object
    EmailRequest:
      example:
        smtp:
          proxy: https://openapi-generator.tech
          hello_name: localhost
          port: 25
          timeout_response: 6.027456183070403
          timeout_connection: 0.8008281904610115
          email_from: user@example.org
        email: SOME.EXISTING.EMAIL@domain.com
      properties:
        email:
          example: SOME.EXISTING.EMAIL@domain.com
          type: string
        smtp:
          $ref: '#/components/schemas/EmailRequest_smtp'
        result_type:
          $ref: '#/components/schemas/ResultType'
      type: object
    EmailResponse:
      oneOf:
      - $ref: '#/components/schemas/CheckIfEmailExistResult'
      - $ref: '#/components/schemas/MailboxvalidatorResult'
      - $ref: '#/components/schemas/PromptEmailVerificationApiResult'
    EmailRequest_smtp:
      example:
        proxy: https://openapi-generator.tech
        hello_name: localhost
        port: 25
        timeout_response: 6.027456183070403
        timeout_connection: 0.8008281904610115
        email_from: user@example.org
      properties:
        email_from:
          default: user@example.org
          example: user@example.org
          format: email
          type: string
        hello_name:
          default: localhost
          example: localhost
          type: string
        proxy:
          description: |
            Versions - SOCKS4, SOCKS4A and SOCKS5.
            Format -  schema://username:password@host:port.
          format: uri
          type: string
        timeout_connection:
          default: 5.0
          description: timeout creating smtp connection
          type: number
        timeout_response:
          description: timeout of communication with smtp server
          type: number
        port:
          default: 25
          description: smtp port remote server
          example: 25
          format: int32
          type: integer
      type: object
  securitySchemes:
    AuthKey:
      in: header
      name: Authorization
      type: apiKey
    RapidApiSecret:
      in: header
      name: X-RapidAPI-Proxy-Secret
      type: apiKey
    RapidApiKey:
      in: header
      name: X-RapidAPI-Key
      type: apiKey
