/*
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckIfEmailExistMisc struct {
	IsDisposable  bool `json:"is_disposable,omitempty"`
	IsRoleAccount bool `json:"is_role_account,omitempty"`
}
