# coding: utf-8

# flake8: noqa
"""
    Email Validator

    All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.check_if_email_exist_mx import CheckIfEmailExistMX
from swagger_client.models.check_if_email_exist_misc import CheckIfEmailExistMisc
from swagger_client.models.check_if_email_exist_result import CheckIfEmailExistResult
from swagger_client.models.check_if_email_exist_smtp import CheckIfEmailExistSMTP
from swagger_client.models.check_if_email_exist_syntax import CheckIfEmailExistSyntax
from swagger_client.models.email_request import EmailRequest
from swagger_client.models.email_request_smtp import EmailRequestSmtp
from swagger_client.models.email_response import EmailResponse
from swagger_client.models.mailboxvalidator_result import MailboxvalidatorResult
from swagger_client.models.one_of_email_response import OneOfEmailResponse
from swagger_client.models.prompt_email_verification_api_mx import PromptEmailVerificationApiMX
from swagger_client.models.prompt_email_verification_api_result import PromptEmailVerificationApiResult
from swagger_client.models.result_type import ResultType
from swagger_client.models.unexpected_error import UnexpectedError
