# coding: utf-8

"""
    Email Validator

    All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CheckIfEmailExistMX(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accepts_mail': 'bool',
        'records': 'list[str]'
    }

    attribute_map = {
        'accepts_mail': 'accepts_mail',
        'records': 'records'
    }

    def __init__(self, accepts_mail=None, records=None):  # noqa: E501
        """CheckIfEmailExistMX - a model defined in Swagger"""  # noqa: E501
        self._accepts_mail = None
        self._records = None
        self.discriminator = None
        if accepts_mail is not None:
            self.accepts_mail = accepts_mail
        if records is not None:
            self.records = records

    @property
    def accepts_mail(self):
        """Gets the accepts_mail of this CheckIfEmailExistMX.  # noqa: E501


        :return: The accepts_mail of this CheckIfEmailExistMX.  # noqa: E501
        :rtype: bool
        """
        return self._accepts_mail

    @accepts_mail.setter
    def accepts_mail(self, accepts_mail):
        """Sets the accepts_mail of this CheckIfEmailExistMX.


        :param accepts_mail: The accepts_mail of this CheckIfEmailExistMX.  # noqa: E501
        :type: bool
        """

        self._accepts_mail = accepts_mail

    @property
    def records(self):
        """Gets the records of this CheckIfEmailExistMX.  # noqa: E501


        :return: The records of this CheckIfEmailExistMX.  # noqa: E501
        :rtype: list[str]
        """
        return self._records

    @records.setter
    def records(self, records):
        """Sets the records of this CheckIfEmailExistMX.


        :param records: The records of this CheckIfEmailExistMX.  # noqa: E501
        :type: list[str]
        """

        self._records = records

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckIfEmailExistMX, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckIfEmailExistMX):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
