# coding: utf-8

"""
    Email Validator

    All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CheckIfEmailExistSyntax(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'domain': 'str',
        'is_valid_syntax': 'bool',
        'username': 'str'
    }

    attribute_map = {
        'address': 'address',
        'domain': 'domain',
        'is_valid_syntax': 'is_valid_syntax',
        'username': 'username'
    }

    def __init__(self, address=None, domain=None, is_valid_syntax=None, username=None):  # noqa: E501
        """CheckIfEmailExistSyntax - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._domain = None
        self._is_valid_syntax = None
        self._username = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if domain is not None:
            self.domain = domain
        if is_valid_syntax is not None:
            self.is_valid_syntax = is_valid_syntax
        if username is not None:
            self.username = username

    @property
    def address(self):
        """Gets the address of this CheckIfEmailExistSyntax.  # noqa: E501


        :return: The address of this CheckIfEmailExistSyntax.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CheckIfEmailExistSyntax.


        :param address: The address of this CheckIfEmailExistSyntax.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def domain(self):
        """Gets the domain of this CheckIfEmailExistSyntax.  # noqa: E501


        :return: The domain of this CheckIfEmailExistSyntax.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this CheckIfEmailExistSyntax.


        :param domain: The domain of this CheckIfEmailExistSyntax.  # noqa: E501
        :type: str
        """

        self._domain = domain

    @property
    def is_valid_syntax(self):
        """Gets the is_valid_syntax of this CheckIfEmailExistSyntax.  # noqa: E501


        :return: The is_valid_syntax of this CheckIfEmailExistSyntax.  # noqa: E501
        :rtype: bool
        """
        return self._is_valid_syntax

    @is_valid_syntax.setter
    def is_valid_syntax(self, is_valid_syntax):
        """Sets the is_valid_syntax of this CheckIfEmailExistSyntax.


        :param is_valid_syntax: The is_valid_syntax of this CheckIfEmailExistSyntax.  # noqa: E501
        :type: bool
        """

        self._is_valid_syntax = is_valid_syntax

    @property
    def username(self):
        """Gets the username of this CheckIfEmailExistSyntax.  # noqa: E501


        :return: The username of this CheckIfEmailExistSyntax.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this CheckIfEmailExistSyntax.


        :param username: The username of this CheckIfEmailExistSyntax.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckIfEmailExistSyntax, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckIfEmailExistSyntax):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
